FREAC/LABINS

- script.js
- styles.css
tasks completed: 
-    change print widget css
-    alter layer ids in Control Lines to reflect removed sublayers from service
> Print widget css

- script.js
> Fixed layer numbers for the features that were messed up

- index.html
- infopanel.js
- script.js
- styles.css
Merge in first try at the Data Query feature. This functions for NGS Control Points at the present time.
> Data query

- index.html
- script.js
Insert CCR data query, insert toggle panel function to toggle current panel off and toggle identifypanel on
> Data query ccr

- script.js
I also renamed the labinsLayer to controlPointsLayer.
> Removed AGO url, extra NGS Points url and ECL line symbol.

- index.html
- infopanel.js
- script.js
Add goback button
Add dataquery capabilities for ECL and survey benchmarks
> add goback to information panel button

- script.js
changed some fields in the Survey Benchmarks, but still not working as expected. 
This pull request is also going to function as a test to see if I can merge a branch again after making an additional commit after having already merged to master.
> troubleshoot survey benchmarks

- infopanel.js
Fixed the datasheet2 link to DATA_SRCE on line 50 of the infopanel.js file.
> Map con datasheet

- script.js
Implement check service functionality to check if services are online before putting them into identify tasks. This will prevent the IdentifyTask functionality from breaking if a service is offline. It will just ignore it.
> Check service

- bookmarks.html
- index.html
- infopanel.js
- scratch.html
- scratch.js
- script.js
- styles.css
Update master with most up to date code.
> Map con scrollable info panel

- infopanel.js
- script.js
tweak response when no features are found so information panel will update to reflect no features are found.
> tweak info panel reset when no features are found on identify

- coords.html
- index.html
- infopanel.js
- script.js
- styles.css
This introduces logic to control zooming depending on if the current extent is closer or farther than target polygon or polyline
> Master coordinates zoomcontrol

- script.js
merge new expander widget functionality into use the coords widget, layerlist widget, legend widget
> Master coordinates expand

- infopanel.js
- script.js
Fix issue #93. Needed to be fixed in this branch because this is where new map services are included
> Certified corner identify

- calciteSample.html
- expandfinal.html
- index.html
- infopanel.js
- script.js
- styles.css
- change viewing for legend and layerlist based on whether the user is on a small screen or a desktop
- update code to 4.9
- point layers to new services on updated 10.6 server
- beautify code
- update css for panel stylings
> Alter layerlegend menuitem visibility

- calciteSample.html
- index.html
- infopanel.js
- measurementwidget.html
- requests.html
- samples/multisourceIdentify.html
- script.js
- styles.css
update to 4.10
add measurement widgets inside of panels
code cleanup to remove unused/dead code
introduce async/await to manage asynchronous activities
> Production

- index.html
- sample.html
- script.js
- styles.css
This PR addresses the issue of #106, #107, and #108.
Now, the layerlist and legend do not overflow the screen, they have sticky headers, and close buttons.
> Layerlist legendrevamp

- docs/samples/opacity.html
- index.html
- infopanel.js
- script.js
Added:
- A button at the top of the map that toggles google street view. 
- When toggled on, identify is disabled and instead a new streetview tab opens on a map click
- Button must be toggled off to re-enable identify. 
Please let me know what you all think of this functionality. I just opened this PR to start the conversation of changes necessary :-)
> Toggle google streetview

- infopanel.js
- script.js
- Default coordinate conversion widget to expanded when user opens the widget. 
- added additional State Plane East/West/North conversions for in meters.
> Coordinate conversion changes

- docs/samples/overviewMap.html
- script.js
* Added overview map sample that is adapted from a sceneview
* Updated overview map to include code from [this](https://developers.arcgis.com/javascript/latest/sample-code/overview-map/index.html) sample
> Refactor overview map

- script.js
Hi everyone,
I've added labels to the Hi Res layers in a branch that came off of the master.
I honestly have no idea which branch is the current one in production, so I'm opening this pull request. :)
> Hires label

- script.js
coordExpand isn't defined on mobile view, so I created some logic to get around that.
> #136 undefined caused identifytask to fail on mobile

- infopanel.js
- script.js
> Remove zoom btn polygons

- infopanel.js
Fixing issue #149. Wrong field called for Quad ID.
> #149 reference the correct Quad id field

- script.js
> #156 change  legend span id

- script.js
changing label for survey benchmarks
> #155 fix label for survey benchmarks

- infopanel.js
#153 reverting back to what is current in production at this time
> #153 always link to MHW and MLW data request form

- script.js
Call ECL layer directly instead of beating around the bush to do an intersect (which has been commented that it won't work in all cases anyway)
> #154 need to call ECL layer directly to get geometry of it

- infopanel.js
first stab at accounting for null ecl lines. initial testing has been successful
> #161 account for null ecl lines

- script.js
previously checking for screen size broke the identify. this was a scope problem. the measurement variable needed to be defined in the global scope so it would be available for the check that is done for the measurement state on a map click.
More testing still needed, just figured this out at the end of my work session.
> #178 change scope of measurement variable

- index.html
- infopanel.js
- script.js
- styles.css
an improvement from https://github.com/FREAC/LABINS/pull/175 where this approach only uses vanilla js and requires no other dependencies.
> #170/toggle overview map

- index.html
- script.js
just changing text on the screen when the hide / show overview map button is clicked.
> change the innerHTML for the hide/show overview map

- index.html
removing the reference and link to the flex map
> #187 remove reference to flex website

- styles.css
I changed it slightly to mimic what the button looks like when you hover over it.
> #180 add colors when measurement widgets area/distance are active

- infopanel.js
- script.js
Minus some console logs, I think we're back to functioning properly between the click identify, search bar, and data query panel!
> #197/ccr zoom fix

- infopanel.js
- script.js
> #204/ccr labels

- index.html
- infopanel.js
- script.js
1) button to allow slow fade of highlighted stuff on a zoom to feature.
2) fixed code to allow zooming to NGS points (NGS layer served by NOAA is on lat/lon)
3) fixed code to show an OPUS link of one exists for a NGS point
> Fade highlights out

- infopanel.js
there was a random console log that needed to be removed and adding a pdf link to cccl infopanel features
> removing console log and adding pdf link to cccl infopanel widget #217

- infopanel.js
- script.js
this includes the mhw info panel section for #216 
also a label change for the measurement tools
> mhw #216 updates
